Models/FollowUp.cs
using System;
using System.Collections.Generic;

namespace Follow_Up_Manager.Models;

public partial class FollowUp
{
    public long Id { get; set; }

    public long? UserId { get; set; }

    public string? Name { get; set; }

    public string? Project { get; set; }

    public string? StartDate { get; set; }

    public string? FollowUpDate { get; set; }

    public string Task { get; set; } = null!;

    public long? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}

Models/ViewModels/FollowUpViewModel.cs
namespace Follow_Up_Manager.Models.ViewModels;

public class FollowUpViewModel
{
    public long? Id { get; set; }

    public long? UserId { get; set; }

    public string? Name { get; set; }

    public string? Project { get; set; }
    public string? Task { get; set; }

    public string? StartDate { get; set; }

    public int? Status {get; set;}

    public string? FollowUpDate { get; set; }
}

Controllers/FollowUpController.cs
using Microsoft.AspNetCore.Mvc;
using Follow_Up_Manager.Models.ViewModels;
using Follow_Up_Manager.interfaces;
using Microsoft.AspNetCore.Authorization;
using System.Text.Json;
using AspNetCoreHero.ToastNotification.Abstractions;


namespace Follow_Up_Manager.Controllers;
[Authorize]
public class FollowUpController : Controller
{
    private readonly IFollowUpService _followUpService;
    public INotyfService _notifyService { get; }

    public FollowUpController(IFollowUpService followUpService, INotyfService notifyService)
    {
        _followUpService = followUpService;
        _notifyService = notifyService;
    }

    public async Task<IActionResult> Index()
    {
        try
        {
            var dataList = await _followUpService.GetAllFollowUps();

            var marked = new List<FollowUpViewModel>();
            var notMarked = new List<FollowUpViewModel>();

            foreach(var data in dataList)
            {
                if(data.Status == 0)
                {
                    notMarked.Add(data);
                }
                else{
                    marked.Add(data);
                }
            }

            ViewBag.marked = marked;
            ViewBag.notMarked = notMarked;

            return View();
        }
        catch (Exception e)
        {
            _notifyService.Error("Something Went Wrong");
            return View();
        }

    }


    public IActionResult Create()
    {
        try
        {
            return View();
        }
        catch (Exception e)
        {
            _notifyService.Error("Something Went Wrong");
            return RedirectToAction("Index");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Create(FollowUpViewModel followUpViewModel)
    {
        try
        {
            string dateString1 = followUpViewModel.StartDate;
            string dateString2 = followUpViewModel.FollowUpDate;

            DateTime date1 = DateTime.ParseExact(dateString1, "dd-MM-yyyy", null);
            DateTime date2 = DateTime.ParseExact(dateString2, "dd-MM-yyyy", null);


            if (date1 >= date2)
            {
                TempData["start_date"] = "Start date should be less than followup date";
                TempData["follow_up_date"] = "Follow Up date should be greater than start date";
                _notifyService.Error("Invalid Start Date & Follow Up Date");
                return RedirectToAction("Create");
            }

            var isStored = await _followUpService.StoreFollowUp(followUpViewModel);
            if (!isStored)
            {
                _notifyService.Error("Follow Up Save Failed");
                return RedirectToAction("Index");
            }
            _notifyService.Success("Follow Up Saved Successfully!");
            return RedirectToAction("Index");
        }
        catch (FormatException ex)
        {
            _notifyService.Error("Something went wrong");
            return RedirectToAction("Index");
        }


    }

    public async Task<IActionResult> Edit(int id)
    {
        try
        {
            var followUpViewModel = await _followUpService.GetFollowUpById(id);
            if (followUpViewModel.Id == 0)
            {
                _notifyService.Error("Invalid Follow up to Edit");
                return RedirectToAction("Index");
            }

            ViewBag.FollowUpViewModel = followUpViewModel;
            return View();

        }
        catch (Exception e)
        {
            _notifyService.Error("Something went wrong");
            return RedirectToAction("Index");
        }

    }

    [HttpPost]
    public async Task<IActionResult> Edit(FollowUpViewModel followUpViewModel)
    {
        try
        {
            string dateString1 = followUpViewModel.StartDate;
            string dateString2 = followUpViewModel.FollowUpDate;

            DateTime date1 = DateTime.ParseExact(dateString1, "dd-MM-yyyy", null);
            DateTime date2 = DateTime.ParseExact(dateString2, "dd-MM-yyyy", null);


            if (date1 >= date2)
            {
                TempData["start_date"] = "Start date should be less than followup date";
                TempData["follow_up_date"] = "Follow Up date should be greater than start date";
                _notifyService.Error("Invalid startdate & followup date");
                return RedirectToAction("Edit");
            }


            await _followUpService.UpdateFollowUp(followUpViewModel);
            _notifyService.Success("follow up updated");
            return RedirectToAction("Index");

        }
        catch (Exception e)
        {
            _notifyService.Error("Something went wrong");
            return RedirectToAction("Index");

        }

    }


    public async Task<IActionResult> View(FollowUpViewModel followUpViewModel)
    {
        try
        {
            var followUp = await _followUpService.GetFollowUpById(Convert.ToInt32(followUpViewModel.Id));
            var activityLogs = await _followUpService.GetActivityLogsByFollowUpId(Convert.ToInt32(followUpViewModel.Id));

            List<ActivityLogViewModel> viewModels = new List<ActivityLogViewModel>();

            foreach (var activityLog in activityLogs)
            {
                ActivityLogViewModel viewModel = new ActivityLogViewModel();
                viewModel.Id = activityLog.Id;
                viewModel.UserId = activityLog.UserId;
                viewModel.FollowUpId = activityLog.FollowUpId;
                viewModel.Description = activityLog.Description;
                List<string>? deserializedList = JsonSerializer.Deserialize<List<string>>(activityLog.Description);
                viewModel.HistoryList = deserializedList;
                viewModel.CreatedAt = activityLog.CreatedAt;
                viewModel.UpdatedAt = activityLog.UpdatedAt;
                viewModels.Add(viewModel);
            }
            FollowUpViewModel model = new FollowUpViewModel();

            model.Id = followUp.Id;
            model.Name = followUp.Name;
            model.UserId = followUp.UserId;
            model.StartDate = followUp.StartDate;
            model.FollowUpDate = followUp.FollowUpDate;
            model.Project = followUp.Project;
            model.Task = followUp.Task;

            ViewBag.FollowUpViewModel = model;
            ViewBag.activityLogs = viewModels;
            return View();
        }
        catch (Exception e)
        {
            _notifyService.Error("Something went wrong");
            return RedirectToAction("Index");
        }


    }


    public async Task<IActionResult> Mark(int id)
    {
        try{

            var followUpViewModel = await _followUpService.GetFollowUpById(id);
            
            if (followUpViewModel.Id == 0)
            {
                _notifyService.Error("Invalid Follow up to Edit");
                return RedirectToAction("Index");
            }

            var isMarked = await _followUpService.MarkFollowUp(id);
            if(!isMarked)
            {
                _notifyService.Error("Marking Failed");
                return RedirectToAction("Index");
            }

            _notifyService.Success("Marked followup succesfully!!!");
            return RedirectToAction("Index");

        }catch(Exception e)
        {
            _notifyService.Error("Something went wrong");
            return RedirectToAction("Index");
        }

    }





}

Views/FollowUp/Create.cshtml
@model Follow_Up_Manager.Models.ViewModels.FollowUpViewModel;
@{
    ViewData["Title"] = "Create Follow Up";
}
<div id="content">
    <div class="container-fluid">
        <main>
            <header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
                <div class="container-xl px-4">
                    <div class="page-header-content pt-4">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto mt-4">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="edit-3"></i></div>
                                    Follow Up
                                </h1>
                                @* <div class="page-header-subtitle my-2">Provide necessary inputs to create a follow
                                up</div> *@
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-xl px-4 mt-n10">
                <div class="row">
                    <div class="col-lg-9">
                        <!-- Default Bootstrap Form Controls-->
                        <div id="default">
                            <div class="card mb-4">
                                <div class="card-header">Provide necessary inputs to create a follow up</div>
                                <div class="card-body">
                                    <!-- Component Preview-->
                                    <div class="sbp-preview">
                                        <div class="sbp-preview-content">
                                            <form asp-action="Create" method="post">
                                                <div class="mb-3">
                                                    <label asp-for="Task">Task</label>
                                                    <input class="form-control" id="task" asp-for="Task" type="text"
                                                        placeholder="Your Task" />
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="StartDate">Start Date</label>
                                                    <input class="form-control" id="start_date" asp-for="StartDate"
                                                        type="text" placeholder="Select Start Date">
                                                        @if(TempData["start_date"] != null)
                                                        {
                                                            <span class="text-danger">@TempData["start_date"]</span>
                                                        }
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="FollowUpDate">Follow Up Date</label>
                                                    <input class="form-control" id="follow_up_date"
                                                        asp-for="FollowUpDate" type="text"
                                                        placeholder="Select follow up Date">
                                                         @if(TempData["follow_up_date"] != null)
                                                        {
                                                            <span class="text-danger">@TempData["follow_up_date"]</span>
                                                        }
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="Name">Name</label>
                                                    <input class="form-control" id="name" asp-for="Name" type="text"
                                                        placeholder="Your Name" />
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="Project">Project</label>
                                                    <input class="form-control" id="project" asp-for="Project"
                                                        type="text" placeholder="Your Project" />
                                                </div>

                                                <div class="mb-3">
                                                    <button class="btn btn-sm btn-primary" type="submit">Submit</button>
                                                </div>
                                            </form>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </main>
    </div>
</div>

@section Scripts {

    <!-- Add Bootstrap Datepicker CSS and JS links -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <script>
        // Activate the datepicker
        $(document).ready(function () {
            $('#start_date').datepicker({
                format: 'dd-mm-yyyy', onSelect: function (selectedDate) {
                    $(this).datepicker("option", "minDate", selectedDate);
                    $('#follow_up_date').datepicker("option", "maxDate", selectedDate);
                }
            });
            $('#follow_up_date').datepicker({
                format: 'dd-mm-yyyy', onSelect: function (selectedDate) {
                    $('#start_date').datepicker("option", "minDate", selectedDate);
                }
            });
        });
    </script>
}

Views/FollowUp/Edit.cshtml
@model Follow_Up_Manager.Models.ViewModels.FollowUpViewModel;
@{
    ViewData["Title"] = "Edit Follow Up";
}
<div id="content">
    <div class="container-fluid">
        <main>
            <header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
                <div class="container-xl px-4">
                    <div class="page-header-content pt-4">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto mt-4">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="edit-3"></i></div>
                                    Edit Follow Up
                                </h1>
                                @* <div class="page-header-subtitle my-2">Provide necessary inputs to create a follow
                                up</div> *@
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-xl px-4 mt-n10">
                <div class="row">
                    <div class="col-lg-9">
                        <!-- Default Bootstrap Form Controls-->
                        <div id="default">
                            <div class="card mb-4">
                                <div class="card-header">Provide necessary inputs to Edit a follow up</div>
                                <div class="card-body">
                                    <!-- Component Preview-->
                                    <div class="sbp-preview">
                                        <div class="sbp-preview-content">
                                            <form asp-action="Edit" asp-route-id="@ViewBag.FollowUpViewModel.Id"
                                                method="post">
                                                <div class="mb-3">
                                                    <label asp-for="Task">Task</label>
                                                    <input class="form-control" id="task" asp-for="Task" type="text"
                                                        value="@ViewBag.FollowUpViewModel.Task" readonly />
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="StartDate">Start Date</label>
                                                    <input class="form-control" id="start_date" asp-for="StartDate"
                                                        type="text" value="@ViewBag.FollowUpViewModel.StartDate">
                                                        @if(TempData["start_date"] != null)
                                                        {
                                                            <span class="text-danger">@TempData["start_date"]</span>
                                                        }
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="FollowUpDate">Follow Up Date</label>
                                                    <input class="form-control" id="follow_up_date"
                                                        asp-for="FollowUpDate" type="text"
                                                        value="@ViewBag.FollowUpViewModel.FollowUpDate">
                                                         @if(TempData["follow_up_date"] != null)
                                                        {
                                                            <span class="text-danger">@TempData["follow_up_date"]</span>
                                                        }
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="Name">Name</label>
                                                    <input class="form-control" id="name" asp-for="Name" type="text"
                                                        value="@ViewBag.FollowUpViewModel.Name" />
                                                </div>

                                                <div class="mb-3">
                                                    <label asp-for="Project">Project</label>
                                                    <input class="form-control" id="project" asp-for="Project"
                                                        type="text" value="@ViewBag.FollowUpViewModel.Project" />
                                                </div>

                                                <div class="mb-3">
                                                    <button class="btn btn-sm btn-primary" type="submit">Update</button>
                                                </div>
                                            </form>
                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </main>
    </div>
</div>

@section Scripts {

    <!-- Add Bootstrap Datepicker CSS and JS links -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <script>
        // Activate the datepicker
        $(document).ready(function () {
            $('#start_date').datepicker({
                format: 'dd-mm-yyyy', onSelect: function (selectedDate) {
                    $(this).datepicker("option", "minDate", selectedDate);
                    $('#follow_up_date').datepicker("option", "maxDate", selectedDate);
                }
            });
            $('#follow_up_date').datepicker({
                format: 'dd-mm-yyyy', onSelect: function (selectedDate) {
                    $('#start_date').datepicker("option", "minDate", selectedDate);
                }
            });
        });
    </script>
}

Views/FollowUp/Index.cshtml
@model Follow_Up_Manager.Models.ViewModels.FollowUpViewModel;

@{
    ViewData["Title"] = "Follow Up List";
}

<div id="content">
    <div>

        @if (TempData["success"] != null)
        {
            @* <script src="/lib/jquery//dist/jquery.js"></script> *@
            <script src="~/Theme/vendor/jquery/jquery.min.js"></script>
            @* <script src="https//cdnj.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.mis.js"></script> *@
            <script type="text/javascrpt">
                    console.log("am i nayem ok?");
                    toastr.success('@TempData["success"]')
                </script>
        }
    </div>

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        @* <h1 class="h3 mb-2 text-gray-800">Tables</h1>
        <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
        href="https://datatables.net">official DataTables documentation</a>.</p> *@



        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-md-10">
                        <h6 class="m-0 font-weight-bold text-primary">Follow Up List</h6>
                    </div>
                    <div class="col-md-2">
                        @* <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> *@
                        <a asp-controller="FollowUp" asp-action="Create"
                            class="btn btn-sm btn-primary btn-sm">Create</a>
                    </div>

                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Task</th>
                                <th>Start Date</th>
                                <th>Follow Up Date</th>
                                <th>Name</th>
                                <th>Project</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Task</th>
                                <th>Start Date</th>
                                <th>Follow Up Date</th>
                                <th>Name</th>
                                <th>Project</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>


                            @foreach (var item in ViewBag.notMarked)
                            {
                                <tr>
                                    <td>@item.Task</td>
                                    <td>@item.StartDate</td>
                                    <td>@item.FollowUpDate</td>
                                    <td>@item.Name</td>
                                    <td>@item.Project</td>
                                    <td>
                                        <a asp-controller="FollowUp" asp-action="View" asp-route-id="@item.Id"
                                            class="btn btn-sm btn-primary">View</a>
                                        <a asp-controller="FollowUp" asp-action="Edit" asp-route-id="@item.Id"
                                            class="btn btn-sm btn-info">Edit</a>
                                        <a asp-controller="FollowUp" asp-action="Mark" asp-route-id="@item.Id"
                                            class="btn btn-sm btn-danger ">Mark</a>
                                    </td>

                                </tr>
                            }

                            @foreach (var item in ViewBag.marked)
                            {
                                <tr>
                                    <td>@item.Task</td>
                                    <td>@item.StartDate</td>
                                    <td>@item.FollowUpDate</td>
                                    <td>@item.Name</td>
                                    <td>@item.Project</td>
                                    <td>
                                        <a asp-controller="FollowUp" asp-action="View" asp-route-id="@item.Id"
                                            class="btn btn-sm btn-primary">View</a>
                                    </td>

                                </tr>
                            }






                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->

</div>

@section Scripts {
    <!-- Page level plugins -->
    <script src="~/Theme/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Theme/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Theme/js/demo/datatables-demo.js"></script>

}